version: '3'
services:
         football-seed:
                build:
                        context: ../
                        dockerfile: docker/cassandra/Dockerfile
                command: bash -c 'if [ -z "$$(ls -A /var/lib/cassandra/)" ] ; then sleep 0; fi && /docker-entrypoint.sh cassandra -f'
                networks:
                        - football-network
                environment:
                        - CASSANDRA_CLUSTER_NAME=dev_cluster
                        - CASSANDRA_SEEDS=football-seed
                ports:
                        - 9042:9042
                expose:
                        - 7199
                        - 9160
                ulimits:
                        memlock: -1
                        nproc: 32768
                        nofile: 100000
                container_name: football-seed
         football-node-1: 
                build:
                        context: ../
                        dockerfile: docker/cassandra/Dockerfile
                command: bash -c 'if [ -z "$$(ls -A /var/lib/cassandra/)" ] ; then sleep 0; fi && /docker-entrypoint.sh cassandra -f'
                networks:
                        - football-network
                environment:
                        - CASSANDRA_CLUSTER_NAME=dev_cluster
                        - CASSANDRA_SEEDS=football-seed
                expose:
                        - 9042
                        - 7199
                        - 9160
                ulimits:
                        memlock: -1
                        nproc: 32768
                        nofile: 100000
                depends_on:
                        - football-seed
                
networks:
        football-network:  
